# Options here can still be overridden by cmd line args.
#   sidekiq -C sidekiq.yml
---
:concurrency: <%= ENV["sidekiq_threads"] || 20 %>
:pidfile: tmp/pids/sidekiq.pid
:queues:
  - [notifications, 100]
  - [http_request, 50]
  - [search_indexer, 30]
  - [mailer, 5]
  - [cleanup, 5]
  - [mailers, 5]
  - [default, 3]
:schedule:
  github_statistics_fetcher:
    cron: "0 0 1 * * *"
    class: Scheduler::GitHubStatisticsFetcherJob
